# -*- coding: utf-8 -*-
"""python_task1_Api_requests.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i3M5JMssPrMpraD9fkPkktLsYWt_QRWE
"""

import requests

API_URL = "https://jsonplaceholder.typicode.com/users"

def main():
    try:

        response = requests.get(API_URL, timeout=10)  #timwout for how many seconds to wait before giving up
        response.raise_for_status()
    except requests.RequestException as e:
        print(f"Error fetching users: {e}")
        return

    try:                        #try except block is used to cover all the errors
        users = response.json()
    except ValueError:
        print("Error: Invalid JSON returned by API")
        return

    for idx, user in enumerate(users, start=1):
        name = user.get("name", "<missing>")
        username = user.get("username", "<missing>")
        email = user.get("email", "<missing>")
        city = user.get("address", {}).get("city", "<missing>")

        if city[0]=='S': #printing only users whose city name starts with S

          print(f"User {idx}:")
          print(f"  Name: {name}")
          print(f"  Username: {username}")
          print(f"  Email: {email}")
          print(f"  City: {city}")
          print("\n")


if __name__ == "__main__":
    main()